export const uk = {
  common: {
    loading: 'Завантаження...',
    error: 'Помилка',
    retry: 'Спробувати знову',
    cancel: 'Скасувати',
    save: 'Зберегти',
    delete: 'Видалити',
    edit: 'Редагувати',
    create: 'Створити',
    search: 'Пошук',
    filter: 'Фільтр',
    clear: 'Очистити',
    apply: 'Застосувати',
    close: 'Закрити',
    back: 'Назад',
    next: 'Далі',
    done: 'Готово',
    yes: 'Так',
    no: 'Ні',
    ok: 'OK',
    confirm: 'Підтвердити',
    share: 'Поділитися',
    refresh: 'Оновити',
    noData: 'Немає даних',
    required: "Обов'язкове поле",
    optional: 'Необов\'язково',
    success: 'Успішно',
    failed: 'Не вдалося',
  },
  
  auth: {
    signIn: 'Увійти',
    signUp: 'Зареєструватися',
    signOut: 'Вийти',
    phone: 'Номер телефону',
    email: 'Електронна пошта',
    password: 'Пароль',
    confirmPassword: 'Підтвердіть пароль',
    forgotPassword: 'Забули пароль?',
    resetPassword: 'Скинути пароль',
    sendCode: 'Надіслати код',
    verifyCode: 'Підтвердити код',
    enterOtp: 'Введіть код з SMS',
    invalidPhone: 'Невірний номер телефону',
    invalidEmail: 'Невірний формат пошти',
    invalidPassword: 'Пароль має містити мінімум 6 символів',
    emailInUse: 'Ця пошта вже використовується',
    userNotFound: 'Користувача не знайдено',
    wrongPassword: 'Невірний пароль',
    invalidCredentials: 'Невірні облікові дані',
    resetEmailSent: 'Лист для скидання пароля надіслано',
    phoneAuth: 'Вхід за номером телефону',
    emailAuth: 'Вхід за поштою',
    orContinueWith: 'або продовжити з',
    demoMode: 'Демо режим: використовуйте код 123456',
  },
  
  navigation: {
    home: 'Головна',
    map: 'Карта',
    myListings: 'Мої',
    messages: 'Повідомлення',
    profile: 'Профіль',
    news: 'Новини',
    admin: 'Адмін',
  },
  
  plots: {
    title: 'Земельні ділянки',
    addPlot: 'Додати ділянку',
    editPlot: 'Редагувати ділянку',
    plotDetails: 'Деталі ділянки',
    myListings: 'Мої оголошення',
    allPlots: 'Всі ділянки',
    approvedPlots: 'Затверджені',
    pendingPlots: 'На модерації',
    rejectedPlots: 'Відхилені',
    draftPlots: 'Чернетки',
    deletedPlots: 'Видалені',
    noPlots: 'Ділянок не знайдено',
    noMyPlots: 'У вас ще немає оголошень',
    createFirst: 'Створіть своє перше оголошення',
    
    fields: {
      title: 'Назва',
      description: 'Опис',
      area: 'Площа',
      areaInSotkas: 'Площа (соток)',
      areaInHectares: 'Площа (га)',
      pricePerSotka: 'Ціна за сотку',
      totalPrice: 'Загальна ціна',
      zone: 'Зона',
      region: 'Регіон',
      oblast: 'Область',
      category: 'Категорія',
      location: 'Розташування',
      address: 'Адреса',
      cadastralNumber: 'Кадастровий номер',
      photos: 'Фотографії',
      owner: 'Власник',
      phone: 'Телефон',
      investment: 'Інвестиційна ділянка',
      credit: 'Доступний кредит',
    },
    
    categories: {
      agricultural: 'Сільськогосподарські',
      residential: 'Житлової забудови',
      commercial: 'Комерційного призначення',
      industrial: 'Промисловості',
      recreational: 'Рекреаційного призначення',
    },
    
    zones: {
      urban_core: 'Міський центр (0-5 км)',
      suburban_0_15: 'Приміська зона (5-15 км)',
      suburban_15_30: 'Приміська зона (15-30 км)',
      rural: 'Сільська місцевість (30+ км)',
    },
    
    status: {
      draft: 'Чернетка',
      pending: 'На модерації',
      approved: 'Затверджено',
      rejected: 'Відхилено',
      deleted: 'Видалено',
    },
    
    marketStatus: {
      below_market: 'Нижче ринку',
      at_market: 'На рівні ринку',
      above_market: 'Вище ринку',
    },
    
    actions: {
      contactOwner: "Зв'язатися з власником",
      openCadastralMap: 'Відкрити кадастрову карту',
      requestInvestment: 'Запит на інвестицію',
      requestCredit: 'Запит на кредит',
      approve: 'Затвердити',
      reject: 'Відхилити',
      delete: 'Видалити',
      restore: 'Відновити',
      publish: 'Опублікувати',
      unpublish: 'Зняти з публікації',
    },
    
    validation: {
      titleRequired: "Назва обов'язкова",
      areaRequired: "Площа обов'язкова",
      priceRequired: "Ціна обов'язкова",
      locationRequired: "Розташування обов'язкове",
      invalidCadastral: 'Невірний формат кадастрового номера',
      cadastralFormat: 'Формат: XXXXXXXXXX:XX:XXX:XXXX',
    },
    
    units: {
      sotka: 'сотка',
      sotkas: 'соток',
      sotky: 'сотки',
      hectare: 'гектар',
      hectares: 'гектарів',
      hectary: 'гектари',
      uah: 'грн',
      uahPerSotka: 'грн/сотка',
      uahPerHectare: 'грн/га',
      km: 'км',
      m: 'м',
    },
    
    pricing: {
      recommendedPrice: 'Рекомендована ціна',
      marketAnalysis: 'Аналіз ринку',
      distanceToCenter: 'Відстань до центру області',
      pricingZone: 'Цінова зона',
      investmentScore: 'Інвестиційний рейтинг',
    },
  },
  
  map: {
    title: 'Карта',
    showCadastral: 'Показати кадастр',
    hideCadastral: 'Сховати кадастр',
    loading: 'Завантаження карти...',
    offline: 'Офлайн режим',
    noPlots: 'На карті немає ділянок',
    selectLocation: 'Оберіть місце на карті',
    currentLocation: 'Моє місцезнаходження',
  },
  
  chat: {
    title: 'Повідомлення',
    noChats: 'У вас ще немає повідомлень',
    startChat: 'Почати чат',
    typeMessage: 'Введіть повідомлення...',
    send: 'Надіслати',
    chatWith: 'Чат з',
    aboutPlot: 'Щодо ділянки',
  },
  
  profile: {
    title: 'Профіль',
    editProfile: 'Редагувати профіль',
    settings: 'Налаштування',
    myListings: 'Мої оголошення',
    favorites: 'Обране',
    notifications: 'Сповіщення',
    language: 'Мова',
    theme: 'Тема',
    about: 'Про додаток',
    help: 'Допомога',
    signOut: 'Вийти',
    deleteAccount: 'Видалити акаунт',
    role: {
      buyer: 'Покупець',
      seller: 'Продавець',
      admin: 'Адміністратор',
      manager: 'Менеджер',
    },
  },
  
    admin: {
      title: 'Панель адміністратора',
      dashboard: 'Дашборд',
      plotsTab: 'Ділянки',
      usersTab: 'Користувачі',
      newsTab: 'Новини',
      analyticsTab: 'Аналітика',
      settings: 'Налаштування',
    
      moderation: {
        title: 'Модерація',
        pending: 'Очікують модерації',
        approve: 'Затвердити',
        reject: 'Відхилити',
        rejectReason: 'Причина відхилення',
        bulkApprove: 'Затвердити всі',
        bulkReject: 'Відхилити всі',
      },
    
      users: {
        title: 'Користувачі',
        block: 'Заблокувати',
        unblock: 'Розблокувати',
        softBan: "М'яка блокування",
        banReason: 'Причина блокування',
        totalUsers: 'Всього користувачів',
        blockedUsers: 'Заблоковані',
        activeUsers: 'Активні',
      },
    
      analytics: {
        totalListings: 'Всього оголошень',
        approvedListings: 'Затверджені',
        pendingListings: 'На модерації',
        rejectedListings: 'Відхилені',
        averagePrice: 'Середня ціна',
        byCategory: 'За категоріями',
        byOblast: 'За областями',
      },
    },
  
  news: {
    title: 'Новини',
    featured: 'Головне',
    latest: 'Останні новини',
    all: 'Всі новини',
    noNews: 'Наразі новин немає',
    readMore: 'Читати далі',
    readingTime: 'хв читання',
    views: 'переглядів',
    publishedAt: 'Опубліковано',
    author: 'Автор',
    share: 'Поділитися',
    relatedNews: 'Схожі новини',
    
    categories: {
      'market-analysis': 'Аналіз ринку',
      'legislation': 'Законодавство',
      'platform-news': 'Новини платформи',
      'investment': 'Інвестиції',
      'other': 'Інше',
    },
    
    admin: {
      title: 'Управління контентом',
      createArticle: 'Створити статтю',
      editArticle: 'Редагувати статтю',
      deleteArticle: 'Видалити статтю',
      publish: 'Опублікувати',
      unpublish: 'Зняти з публікації',
      archive: 'Архівувати',
      markFeatured: 'Позначити як головне',
      unmarkFeatured: 'Зняти з головного',
      
      fields: {
        title: 'Заголовок',
        shortDescription: 'Короткий опис',
        content: 'Зміст',
        category: 'Категорія',
        tags: 'Теги',
        coverImage: 'Обкладинка',
        gallery: 'Галерея',
        status: 'Статус',
        featured: 'Головна новина',
      },
      
      status: {
        draft: 'Чернетка',
        published: 'Опубліковано',
        archived: 'В архіві',
      },
      
      validation: {
        titleRequired: "Заголовок обов'язковий",
        titleTooLong: 'Заголовок занадто довгий (макс. 200 символів)',
        descriptionRequired: "Короткий опис обов'язковий",
        descriptionTooLong: 'Опис занадто довгий (макс. 500 символів)',
        contentRequired: "Зміст обов'язковий",
        contentTooLong: 'Зміст занадто довгий (макс. 50000 символів)',
        categoryRequired: "Категорія обов'язкова",
        imageTooLarge: 'Розмір зображення перевищує 5MB',
        invalidImageType: 'Дозволені формати: JPG, PNG, WebP',
      },
    },
  },
  
  errors: {
    general: 'Щось пішло не так',
    network: 'Помилка мережі. Перевірте підключення.',
    notFound: 'Не знайдено',
    unauthorized: 'Немає доступу',
    forbidden: 'Доступ заборонено',
    serverError: 'Помилка сервера',
    timeout: 'Час очікування вичерпано',
    offline: 'Ви офлайн. Деякі функції недоступні.',
    tryAgain: 'Спробуйте ще раз',
    contactSupport: "Зверніться до служби підтримки",
  },
  
  empty: {
    plots: 'Ділянок не знайдено',
    chats: 'Повідомлень немає',
    news: 'Наразі новин немає',
    search: 'За вашим запитом нічого не знайдено',
    favorites: 'У вас немає обраних ділянок',
    notifications: 'Сповіщень немає',
  },
  
  filters: {
    title: 'Фільтри',
    reset: 'Скинути',
    apply: 'Застосувати',
    priceRange: 'Діапазон цін',
    areaRange: 'Діапазон площі',
    category: 'Категорія',
    oblast: 'Область',
    zone: 'Зона',
    status: 'Статус',
    from: 'Від',
    to: 'До',
    all: 'Всі',
    investment: 'Тільки інвестиційні',
    credit: 'З можливістю кредиту',
    premium: 'Преміум',
  },
  
  dates: {
    today: 'Сьогодні',
    yesterday: 'Вчора',
    daysAgo: 'днів тому',
    weeksAgo: 'тижнів тому',
    monthsAgo: 'місяців тому',
    yearsAgo: 'років тому',
  },
};

export type LocalizationKey = keyof typeof uk;
export default uk;
